### ISSUE TITLE
wow vous etes productifs en ta!

### ISSUE THREAD

**Issue by OlivierFortier** [lynata/tim2020#105]
esti vous avez fait presque 200 commits en quelques jours

**Comment by Aleksios22** [comment]
> esti vous avez fait presque 200 commits en quelques jours
HAHAHAHA merci de l'encourragement. J'pensais pas tu pouvais commenter dememe

**Comment by OlivierFortier** [comment]
I wish I wasnt the only one working on my project :(
faites juste check le nb de commit par moi vs les autres hahahahahahahah....... rip
